# **Video Game Sales**
### Fall 2024 Data Science Project

**Names:** Fahad Haider, Nishkal Hundia, Ishaan Bhardwaj


**Contributions:**

Fahad Haider: Project Idea, Introduction, and Data Curation

Nishkal Hundia: Data Curation, Imputation and Primary Analysis

Ishaan Bhardwaj:

d:

# Introduction

The medium of video games has been growing ever since the 1980s, with old classics such as *Super Mario Bros*, and *The Legend Of Zelda*, and still grows today with modern games such as *Fortnite*. It has become one of the key components of entertainment, standing alongside other media such as movies or books. Our study intends on examinining the gaming industry as of 2016, how video games sales have changed, and how video game companies have evolved, or stagnated, during this time. We'd also be able to see if game sales can be helped or harmed by the platform its on, and we can even see how long a platform "lasts". In essence, our main priority is focusing on how video game sales have grown over these years.

The idea of focusing our study on these aspects is to observe the growth of the video game industry as a whole up to around 2016, seeing if the increase in sales for games is a byproduct of the growth of the industry. It also lets us observe what type of games a company releases and what consoles they release on in order to possibly descern how the company was able to be successful in that era.

The study focuses on the gaming industry up to 2016 because of the fact that the dataset that we use goes up to around that year, with a couple of games on there releasing after that year. The study intends to analyze how the gaming industry grew to that specific point, and further sections will investigate these questions to provide the specific data regarding them.

# Data Curation

The first thing that we need to do is to import the necessary modules in order to work with our dataset, and then import kagglehub to download the dataset that we need.

**Video Game Dataset Source:** https://www.kaggle.com/datasets/rush4ratio/video-game-sales-with-ratings/

In [146]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import scipy.stats as stats
import seaborn as sns

import kagglehub

# Download latest version
path = kagglehub.dataset_download("rush4ratio/video-game-sales-with-ratings")

Next, we will need to read our dataset into a pandas dataframe. This is how we will be able to work with the dataset, and be able to process it so that it can be suitable for analyzing and using machine learning to obtain our results.

In [147]:
# Loads the dataset into a pandas dataframe
games_df = pd.read_csv('/root/.cache/kagglehub/datasets/rush4ratio/video-game-sales-with-ratings/versions/2/Video_Games_Sales_as_at_22_Dec_2016.csv')

# Prints the shape of the dataframe
print("Shape of the DataFrame: ", games_df.shape)

# List of Columns
print("List of columns in the DataFrame: ", games_df.columns)

# Prints small piece of the dataframe
games_df.head()

Shape of the DataFrame:  (16719, 16)
List of columns in the DataFrame:  Index(['Name', 'Platform', 'Year_of_Release', 'Genre', 'Publisher', 'NA_Sales',
       'EU_Sales', 'JP_Sales', 'Other_Sales', 'Global_Sales', 'Critic_Score',
       'Critic_Count', 'User_Score', 'User_Count', 'Developer', 'Rating'],
      dtype='object')

,Name,Platform,Year_of_Release,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales,Critic_Score,Critic_Count,User_Score,User_Count,Developer,Rating
0,Wii Sports,Wii,2006.0,Sports,Nintendo,41.36,28.96,3.77,8.45,82.53,76.0,51.0,8,322.0,Nintendo,E
1,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24,NaN,NaN,NaN,NaN,NaN,NaN
2,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.68,12.76,3.79,3.29,35.52,82.0,73.0,8.3,709.0,Nintendo,E
3,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.61,10.93,3.28,2.95,32.77,80.0,73.0,8,192.0,Nintendo,E
4,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37,NaN,NaN,NaN,NaN,NaN,NaN

We notice that this dataset has some missing data in many places. The description on Kaggle states that data was scraped from both Metacritic and VGCharts, both websites which were established years after some of the video games listed (with VGChartz being made in 2005, and Metacritic being made in 2001), this means that the missing data for columns that relate to a game's metacritic score and rating are Missing At Random, and it is based on the year the game was released.

With this out of the way, we are now going to gather the number of missing values for each column, then compare them to the number of total rows. If the number of rows with missing data in that column is roughly 1-2%, I will simply drop all of the rows with that missing data.

In [148]:
# Print the number of missing data in each column.
missing_data = {}
for i in games_df.columns:
  missing_data[i] = len(games_df[games_df[i].isnull()])
print("Missing Data From Each Column: ", missing_data)

# Print the total number of rows in the dataframe
total_rows = len(games_df)
print("Total number of rows: ", total_rows)

# Creates new dataframe with the intention of dropping the necessary rows
cleaned_df1 = games_df

# Drops only the rows where the null data in a column makes up less than 2% of
# the entire data.
for j in missing_data:
  if missing_data[j] > 0:
    if (missing_data[j] / total_rows) < 0.02:
      cleaned_df1 = cleaned_df1[~(cleaned_df1[j].isnull())]
      total_rows = len(cleaned_df1)

# Print the number of missing data in each column in the new dataframe
missing_data = {}
for i in cleaned_df1.columns:
  missing_data[i] = len(cleaned_df1[cleaned_df1[i].isnull()])
print("Missing Data From Each Column: ", missing_data)

total_rows = len(cleaned_df1)
print("Total number of rows: ", total_rows)

cleaned_df1.head()

Missing Data From Each Column:  {'Name': 2, 'Platform': 0, 'Year_of_Release': 269, 'Genre': 2, 'Publisher': 54, 'NA_Sales': 0, 'EU_Sales': 0, 'JP_Sales': 0, 'Other_Sales': 0, 'Global_Sales': 0, 'Critic_Score': 8582, 'Critic_Count': 8582, 'User_Score': 6704, 'User_Count': 9129, 'Developer': 6623, 'Rating': 6769}
Total number of rows:  16719
Missing Data From Each Column:  {'Name': 0, 'Platform': 0, 'Year_of_Release': 0, 'Genre': 0, 'Publisher': 0, 'NA_Sales': 0, 'EU_Sales': 0, 'JP_Sales': 0, 'Other_Sales': 0, 'Global_Sales': 0, 'Critic_Score': 8434, 'Critic_Count': 8434, 'User_Score': 6579, 'User_Count': 8955, 'Developer': 6512, 'Rating': 6649}
Total number of rows:  16416

,Name,Platform,Year_of_Release,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales,Critic_Score,Critic_Count,User_Score,User_Count,Developer,Rating
0,Wii Sports,Wii,2006.0,Sports,Nintendo,41.36,28.96,3.77,8.45,82.53,76.0,51.0,8,322.0,Nintendo,E
1,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24,NaN,NaN,NaN,NaN,NaN,NaN
2,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.68,12.76,3.79,3.29,35.52,82.0,73.0,8.3,709.0,Nintendo,E
3,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.61,10.93,3.28,2.95,32.77,80.0,73.0,8,192.0,Nintendo,E
4,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37,NaN,NaN,NaN,NaN,NaN,NaN

We have done the easier parts of cleaning our data, however there are still many rows with missing data in some columns, many of which take up the majority of our dataframe.

Before we do any more data cleaning, we will have to drop the columns that we believe are not useful to our analysis. These columns are NA_Sales, EU_Sales, JP_Sales, Other_Sales, Critic_Count, User_Count, and Developer. The first four columns just add up to the Global_Sales column most of the time, which is the only sales data we personally need. With the Critic_Count and User_Count columns, we find that the number of null values take up a great deal of the dataframe. These columns are also not particularly useful at analyzing the gaming industry in the context of its sales growth.

In [149]:
# Drop all the aformentioned columns listed above
cleaned_df1 = cleaned_df1[['Name', 'Platform', 'Year_of_Release', 'Genre', 'Publisher', 'Global_Sales', 'Critic_Score', 'User_Score', 'Developer', 'Rating']]

# Print the number of missing data in each column in the new dataframe
missing_data = {}
for i in cleaned_df1.columns:
  missing_data[i] = len(cleaned_df1[cleaned_df1[i].isnull()])
print("Missing Data From Each Column: ", missing_data)

cleaned_df1.head()

Missing Data From Each Column:  {'Name': 0, 'Platform': 0, 'Year_of_Release': 0, 'Genre': 0, 'Publisher': 0, 'Global_Sales': 0, 'Critic_Score': 8434, 'User_Score': 6579, 'Developer': 6512, 'Rating': 6649}

,Name,Platform,Year_of_Release,Genre,Publisher,Global_Sales,Critic_Score,User_Score,Developer,Rating
0,Wii Sports,Wii,2006.0,Sports,Nintendo,82.53,76.0,8,Nintendo,E
1,Super Mario Bros.,NES,1985.0,Platform,Nintendo,40.24,NaN,NaN,NaN,NaN
2,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,35.52,82.0,8.3,Nintendo,E
3,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,32.77,80.0,8,Nintendo,E
4,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,31.37,NaN,NaN,NaN,NaN

Now, it's a good idea to check for things such as the rating column. There have been changes to ESRB's rating system since its inception, and our goal is to standardize the dataset to make it easier to determine what a game's rating is.

What we will do next is to find all the unique values in the Rating column, to see what needs to be changed.

In [150]:
ratings = cleaned_df1['Rating'].drop_duplicates().values.tolist()
print("Rating:", ratings)

Rating: ['E', nan, 'M', 'T', 'E10+', 'K-A', 'AO', 'EC', 'RP']

According to the ESRB website, K-A was changed into E, and EC tends to be covered under the rating of E, as it is not listed among the main rankings in the esrb wesbite. What I will do now is replace any instances of those with E instead.

In [151]:
# Replaces all instances of K-A and EC with E
print("Number of rows with a rating of E: ", len(cleaned_df1[cleaned_df1.Rating == 'E']))
print("Number of rows with a rating of K-A: ", len(cleaned_df1[cleaned_df1.Rating == 'K-A']))
print("Number of rows with a rating of EC: ", len(cleaned_df1[cleaned_df1.Rating == 'EC']))
cleaned_df1['Rating'] = cleaned_df1['Rating'].str.replace('K-A', 'E')
cleaned_df1['Rating'] = cleaned_df1['Rating'].str.replace('EC', 'E')

print("Number of rows with a rating of E (After replacing): ", len(cleaned_df1[cleaned_df1.Rating == 'E']))

Number of rows with a rating of E:  3921
Number of rows with a rating of K-A:  3
Number of rows with a rating of EC:  8
Number of rows with a rating of E (After replacing):  3932

We can then predict the rating of a game based off of three factors, one being the platform the game has released on, the other being the genre of the game, and another being the publisher of the game.

We will use hot-deck imputation to fill the data in the rating column so that there is no null data there.

Now that we have filled the Rating data, we should focus our attention on the Critic and User Score. First, we should find every unique value to determine any anomalies in both columns. We would like to change the Critic Score column into an int column, and the user score into a float column, so finding any anomolies in the dataframe would be good.

In [152]:
critics = cleaned_df1['Critic_Score'].drop_duplicates().values.tolist()
users = cleaned_df1['User_Score'].drop_duplicates().values.tolist()
print("Critic_Score:", critics)
print("User_Score:", users)

Critic_Score: [76.0, nan, 82.0, 80.0, 89.0, 58.0, 87.0, 91.0, 61.0, 97.0, 95.0, 77.0, 88.0, 83.0, 94.0, 93.0, 85.0, 86.0, 98.0, 96.0, 90.0, 84.0, 73.0, 74.0, 78.0, 92.0, 71.0, 72.0, 68.0, 62.0, 49.0, 67.0, 81.0, 66.0, 56.0, 79.0, 70.0, 59.0, 64.0, 75.0, 60.0, 63.0, 69.0, 50.0, 25.0, 42.0, 44.0, 55.0, 48.0, 57.0, 29.0, 47.0, 65.0, 54.0, 20.0, 53.0, 37.0, 38.0, 33.0, 52.0, 30.0, 32.0, 43.0, 45.0, 51.0, 40.0, 46.0, 39.0, 34.0, 41.0, 36.0, 31.0, 27.0, 35.0, 26.0, 19.0, 28.0, 23.0, 24.0, 21.0, 17.0, 13.0]
User_Score: ['8', nan, '8.3', '8.5', '6.6', '8.4', '8.6', '7.7', '6.3', '7.4', '8.2', '9', '7.9', '8.1', '8.7', '7.1', '3.4', '5.3', '4.8', '3.2', '8.9', '6.4', '7.8', '7.5', '2.6', '7.2', '9.2', '7', '7.3', '4.3', '7.6', '5.7', '5', '9.1', '6.5', 'tbd', '8.8', '6.9', '9.4', '6.8', '6.1', '6.7', '5.4', '4', '4.9', '4.5', '9.3', '6.2', '4.2', '6', '3.7', '4.1', '5.8', '5.6', '5.5', '4.4', '4.6', '5.9', '3.9', '3.1', '2.9', '5.2', '3.3', '4.7', '5.1', '3.5', '2.5', '1.9', '3', '2.7', '2.2', '2', '9.5', '2.1', '3.6', '2.8', '1.8', '3.8', '0', '1.6', '9.6', '2.4', '1.7', '1.1', '0.3', '1.5', '0.7', '1.2', '2.3', '0.5', '1.3', '0.2', '0.6', '1.4', '0.9', '1', '9.7']

Looking through both the unique values of the critic score and user score, we find that for some reason, the user score has a list of strings. The Critic Score has no anomolies except for the null values, however user_score has something known as "tbd". To simplify our dataset, we're going to have to convert any datapoint with "tbd" into null, then we can convert the whole column into a numeric column.

In [155]:
# Changes all data points with tbd in the user score column to be Null.
cleaned_df1['User_Score'] = cleaned_df1['User_Score'].replace('tbd', np.NaN)
# Checks to see if all of the datapoints with tbd have been replaced with a null
# value.
print(len(cleaned_df1[cleaned_df1.User_Score == 'tbd']))

# Casts the user_score to a float data type now that the one anomaly has been
# fixed.
cleaned_df1['User_Score'] = cleaned_df1['User_Score'].astype('float64')

0

# Bibliography

**Dataset Source:** https://www.kaggle.com/datasets/rush4ratio/video-game-sales-with-ratings/

**ESRB Website:** https://www.esrb.org/